document.addEventListener('DOMContentLoaded', () => {
    const searchButton = document.getElementById('searchButton');
    const searchInput = document.getElementById('searchInput');
    const resultsDiv = document.getElementById('results')

    const data ={ "Udaipur": [
        "Hathipole Market",
        "Bapu Bazaar",
        "Rajasthan Art and Craft",
        "Shilpgram",
        "Sukhadiya Circle Market",
        "Karma Art Gallery",
        "Mewar Art Gallery",
        "Brijwasi Mithai Wala",
        "Rajasthan State Handloom Development Corporation",
        "Rajputana Art",
        "Udaipur Handicraft",
        "Hawa Mahal Souvenirs",
        "Jagat Niwas Palace Shop",
        "Rajasthani Ethnic Store",
        "Shree Krishna Textiles",
        "City Palace Souvenirs",
        "Rajasthan Museum Shop",
        "Gulab Bagh Market",
        "Sangeet Arts",
        "The Tea House"
    ],
    "Hampi": [
        "Hampi Bazaar",
        "Mango Tree Restaurant",
        "Shivlinga Handicrafts",
        "Ananya Handicrafts",
        "Kishkindha Trust",
        "Hampi Heritage Center",
        "The Goan Corner",
        "Mysore Silk House",
        "Karnataka State Handicrafts Development Corporation",
        "Hampi Souvenir Shop",
        "Bangalore Handicrafts",
        "Vijayanagar Handicrafts",
        "Hampi Art Gallery",
        "Hampi Silk Weavers",
        "Stone Carvings Shop",
        "Local Artisan Market",
        "Karnataka Handloom",
        "Hampi Crafts Emporium",
        "Heritage Crafts",
        "Ancient Artifacts Shop"
    ],
    "Majuli": [
        "Majuli Handloom Emporium",
        "Satra Bazaar",
        "Majuli Craft Centre",
        "Mishing Handicrafts",
        "Tengapania Market",
        "Dakhinpat Satra Shop",
        "Mishing Tribal Arts",
        "Riverside Souvenir Shop",
        "Jorhat Market",
        "Handloom Weavers’ Co-operative",
        "Majuli Art Gallery",
        "Majuli Souvenir Shop",
        "Kamalabari Satra Shop",
        "Majuli Tribal Handicrafts",
        "Assam Silk House",
        "Rural Artisans Market",
        "Mishing Weaving Centre",
        "Majuli Craft and Art Store",
        "Handmade Goods Shop",
        "Traditional Assamese Goods"
    ],
    "Cherrapunji": [
        "Sohra Craft Centre",
        "Cherrapunji Handicraft Shop",
        "Mawsmai Caves Souvenir Shop",
        "Dawki Market",
        "Living Root Bridge Souvenir Shop",
        "Elephant Falls Souvenir Shop",
        "Shillong Bazaar",
        "Nongthymmai Handloom",
        "Cherrapunji Tribal Crafts",
        "Umiam Lake Market",
        "Krem Mawmluh Souvenir Shop",
        "Krem Phyllut Crafts",
        "Sohra Heritage Shop",
        "Nongriat Village Market",
        "Khasi Tribal Handicrafts",
        "Mawlynnong Market",
        "Living Root Bridge Market",
        "Cherrapunji Traditional Goods",
        "Highland Souvenirs",
        "Meghalaya Craft Centre"
    ],
    "Kutch": [
        "Bhujodi Handicrafts",
        "Kutch Craft Village",
        "Mandvi Beach Market",
        "Kutch Museum Shop",
        "Rann Utsav Crafts",
        "Swaminarayan Temple Bazaar",
        "Rudra Mata Temple Shop",
        "Kutch Bandhej",
        "Rudra Arts and Crafts",
        "Desert Crafts",
        "Kutch Art Centre",
        "Crafts of Kutch",
        "Narayan Sarovar Shop",
        "Kutch Desert Shop",
        "Kutch Heritage Market",
        "Lakhpat Fort Souvenirs",
        "Khambhalida Caves Shop",
        "Traditional Kutch Handlooms",
        "Kutch Craft Emporium",
        "Rann Festival Souvenirs"
    ],
    "Jaisalmer": [
        "Sadar Bazaar",
        "Sonaron Ka Baas",
        "Patwon Ki Haveli Souvenir Shop",
        "Gadisar Lake Market",
        "Desert Handicrafts",
        "Camel Desert Art",
        "Kuldhara Village Shop",
        "Jaisalmer Fort Market",
        "Khuri Village Handicrafts",
        "Rajasthani Ethnic Store",
        "Jaisalmer Souvenirs",
        "Rajputana Jewelry",
        "Desert Safari Souvenirs",
        "Patwa Handloom",
        "Bada Bagh Souvenirs",
        "Camel Leather Crafts",
        "Rajasthani Textiles",
        "Jaisalmer Art Gallery",
        "Desert Crafts Emporium",
        "Traditional Rajasthani Goods"
    ],
    "Delhi": [
        "Connaught Place",
        "Chandni Chowk",
        "Dilli Haat",
        "Karol Bagh",
        "Lajpat Nagar",
        "Janpath",
        "South Extension Market",
        "Sarojini Nagar Market",
        "Paharganj Market",
        "Gurgaon Sector 29 Market",
        "Ansal Plaza",
        "Delhi Street Food",
        "Khan Market",
        "Gaffar Market",
        "Saket District Centre",
        "Rajouri Garden Market",
        "Greater Kailash Market",
        "Indraprastha Park Market",
        "Pragati Maidan Souvenir Shop",
        "Sundar Nagar Market"
    ],
    "Mumbai": [
        "Colaba Causeway",
        "Bandra Linking Road",
        "Crawford Market",
        "Lajpat Nagar Market",
        "Fashion Street",
        "Hill Road",
        "Mumbai Local Markets",
        "Chor Bazaar",
        "Versova Beach Market",
        "Zaveri Bazaar",
        "Dadar Flower Market",
        "Bandra Fort",
        "Kalbadevi Market",
        "Vile Parle Market",
        "Malad Market",
        "Marine Drive Market",
        "Juhu Beach Market",
        "Worli Market",
        "Fort Area Market",
        "Pali Hill Market"
    ],
    "Bangalore": [
        "MG Road",
        "Commercial Street",
        "Brigade Road",
        "Russell Market",
        "UB City",
        "Kormangala",
        "Jayanagar 4th Block",
        "Malleshwaram",
        "Shivajinagar Market",
        "Chickpet Market",
        "Bangalore Palace Market",
        "Garuda Mall",
        "Orion Mall",
        "Bangalore Fort Market",
        "V V Puram Food Street",
        "KR Market",
        "Bangalore Handicrafts",
        "Nehru Place Market",
        "Hosur Road Market",
        "Indiranagar 100 Feet Road"
    ],
    "Hyderabad": [
        "Laad Bazaar",
        "Moazzam Jahi Market",
        "Shahran Market",
        "Jambagh Flower Market",
        "Banjara Hills",
        "Hitec City",
        "MG Road",
        "Sultan Bazaar",
        "Shilparamam",
        "Koti Market",
        "Gachibowli Market",
        "Begum Bazaar",
        "Charminar Market",
        "Secunderabad Market",
        "Husain Sagar Lake Market",
        "Lal Darwaza Market",
        "Malakpet Market",
        "Saroornagar Market",
        "Tank Bund Market",
        "Secunderabad Cantonment Market"
    ],
    "Kolkata": [
        "New Market",
        "Dakshinapan Shopping Complex",
        "Gariahat Market",
        "Park Street",
        "Kolkata Book Fair",
        "Esplanade",
        "South City Mall",
        "City Centre",
        "College Street",
        "Kolkata Handloom",
        "New Alambazar",
        "Kolkata Flower Market",
        "Russel Street",
        "Ballygunge Place",
        "Salt Lake Sector V",
        "Howrah Market",
        "New Town",
        "Burrabazar",
        "Kolkata Crafts Village",
        "Chandni Chowk"
    ],
    "Jaipur": [
        "Johari Bazaar",
        "Tripolia Bazaar",
        "Bapu Bazaar",
        "Raja Park",
        "Mirza Ismail Road",
        "Pink City Market",
        "Jaipur Handloom",
        "Kishanpole Bazaar",
        "Sardar Patel Market",
        "Hawa Mahal Souvenirs",
        "City Palace Souvenirs",
        "Jaipur Textile Market",
        "Chandpole Bazaar",
        "Ramganj Bazaar",
        "Gopal Ji Ka Rasta",
        "M.I. Road Market",
        "Nehru Bazaar",
        "Ganpati Plaza",
        "Sanganeri Print Market",
        "Raja Park Handicrafts"
    ],
    "Agra": [
        "Sadar Bazaar",
        "Kinari Bazaar",
        "Taj Mahal Souvenirs",
        "Agra Fort Market",
        "Jama Masjid Market",
        "Munro Road Market",
        "Raja Ki Mandi",
        "Taj Ganj Market",
        "Subhash Bazaar",
        "Agra Handloom",
        "Shah Jahan Park Market",
        "Agra Textile Market",
        "Local Artisans Market",
        "Dariyaganj Market",
        "Sadar Bazaar Souvenirs",
        "Raja ki Mandi Market",
        "Mahatma Gandhi Road Market",
        "Taj Mahal Crafts",
        "Agra Leather Goods",
        "Local Agra Souvenirs"
    ],
    "Amritsar": [
        "Golden Temple Market",
        "Hall Bazaar",
        "Katra Jaimal Singh",
        "Maharaja Ranjit Singh Museum Shop",
        "Ludhiana Market",
        "Mahatma Gandhi Road Market",
        "Guru Bazaar",
        "Amritsar Handloom",
        "Chowk Fawara",
        "Ranjit Avenue",
        "Kesar Da Dhaba",
        "Amritsar Jewelry Market",
        "Market at Amritsar Railway Station",
        "Ram Bagh Market",
        "Local Artisan Market",
        "Golden Temple Souvenirs",
        "Gurdwara Bazaar",
        "Wagah Border Souvenirs",
        "Local Amritsar Crafts",
        "Amritsar Spices Market"
    ],
    "Bhopal": [
        "Bhopal Haat",
        "New Market",
        "Madhya Pradesh Handloom",
        "Upper Lake Market",
        "Lal Parade Ground Market",
        "DB City Mall",
        "TT Nagar Market",
        "Old Bhopal Market",
        "Habibganj Market",
        "Bhopal Textile Market",
        "Bhopal Souvenir Shop",
        "Local Artisan Crafts",
        "MP Nagar Market",
        "Raja Bhoj Market",
        "Local Handloom Market",
        "Bhopal Handicrafts",
        "Gautam Nagar Market",
        "Local Food Street",
        "Bhopal Arts and Crafts",
        "Bhopal Heritage Souvenirs"
    ],
    "Dehradun": [
        "Paltan Bazaar",
        "Rajpur Road",
        "Clock Tower Market",
        "Kashmiri Handicrafts",
        "Malsi Deer Park Market",
        "Local Artisan Market",
        "Dehradun Haat",
        "Clemens Market",
        "Chakrasia Market",
        "Local Souvenir Shop",
        "Paltan Bazaar Souvenirs",
        "Doon Handloom",
        "Bhagirath Palace Market",
        "Dehradun Handicrafts",
        "Raja ji National Park Souvenirs",
        "Tibetan Market",
        "GMS Road Market",
        "Dehradun Traditional Goods",
        "Rajpur Handicrafts",
        "Local Dehradun Crafts",
        "Dehradun Food Street"
    ],
    "Shimla": [
        "Mall Road",
        "Lakkar Bazaar",
        "The Ridge Market",
        "Shimla Handloom",
        "Lower Bazaar",
        "Kufri Market",
        "Local Artisan Market",
        "Chowkhandi Market",
        "Tara Devi Temple Shop",
        "Shimla Souvenirs",
        "Local Handicrafts",
        "Summer Hill Market",
        "Sanjauli Market",
        "Shimla Textile Market",
        "Indian Institute of Advanced Study Market",
        "Viceregal Lodge Market",
        "Shimla Crafts Emporium",
        "Local Food Street",
        "Local Handloom Goods",
        "Shimla Heritage Souvenirs"
    ],
    "Srinagar": [
        "Dal Lake Market",
        "Lal Chowk",
        "Nehru Place Market",
        "Kashmiri Handicrafts",
        "Shankaracharya Temple Shop",
        "Local Souvenir Shop",
        "Srinagar Haat",
        "Jammu Road Market",
        "Kashmiri Shawls Market",
        "Srinagar Art Gallery",
        "Local Artisans Market",
        "Meadow Market",
        "Kashmiri Carpets",
        "Local Jewelry Shop",
        "Srinagar Crafts Emporium",
        "Mughal Gardens Souvenirs",
        "Srinagar Food Street",
        "Local Textile Market",
        "Kashmiri Spices Shop",
        "Srinagar Heritage Souvenirs"
    ],
    "Gangtok": [
        "MG Road",
        "Local Handicrafts Market",
        "Enchey Monastery Shop",
        "Gangtok Haat",
        "Local Souvenir Shop",
        "Tibetan Market",
        "Ranka Monastery Souvenirs",
        "Gangtok Art Gallery",
        "Local Textile Shop",
        "Tibetan Handicrafts",
        "Local Crafts Emporium",
        "Junction Market",
        "Gangtok Food Street",
        "Namgyal Institute of Tibetology Shop",
        "Local Artisans Market",
        "Sikkim Handloom Market",
        "M.G. Marg Market",
        "Local Jewelry Shop",
        "Gangtok Spices Shop",
        "Sikkim Heritage Souvenirs"
    ],
    "Darjeeling": [
        "Mall Road",
        "Chowrasta",
        "Local Handicrafts Market",
        "Darjeeling Haat",
        "Tibetan Market",
        "Local Souvenir Shop",
        "Darjeeling Art Gallery",
        "Local Textile Shop",
        "Tibetan Handicrafts",
        "Darjeeling Handloom",
        "Local Crafts Emporium",
        "Rink Mall",
        "Darjeeling Food Street",
        "Batasia Loop Market",
        "Local Jewelry Shop",
        "Himalayan Mountaineering Institute Market",
        "Local Artisans Market",
        "Tibetan Carpet Market",
        "Darjeeling Heritage Souvenirs",
        "Sikkim Handloom Market"]
            
    };

    searchButton.addEventListener('click', () => {
        const query = searchInput.value.trim().toLowerCase();
        resultsDiv.innerHTML = '';

        if (query) {
            const results = Object.entries(data).filter(([place, items]) =>
                place.toLowerCase().includes(query)
            );

            if (results.length > 0) {
                resultsDiv.innerHTML = results.map(([place, items]) => `
                    <div class="place">
                        <h3>${place}</h3>
                        <ul>
                            ${items.map(item => `<li>${item}</li>`).join('')}
                        </ul>
                    </div>
                `).join('');
            } else {
                resultsDiv.innerHTML = '<p>No results found.</p>';
            }
        } else {
            resultsDiv.innerHTML = '<p>Please enter a search term.</p>';
        }
    });
});


    searchButton.addEventListener('click', () => {
        const query = searchInput.value.trim().toLowerCase();
        resultsDiv.innerHTML = '';

        if (query) {
            const filteredResults = data.filter(item => item.toLowerCase().includes(query));
            if (filteredResults.length > 0) {
                resultsDiv.innerHTML = filteredResults.map(result => `<p>${result}</p>`).join('');
            } else {
                resultsDiv.innerHTML = '<p>No results found.</p>';
            }
        } else {
            resultsDiv.innerHTML = '<p>Please enter a search term.</p>';
        }
    });